name: CI Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.set_version.outputs.version }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '25.x'
      
      - name: Set Version and Owner
        id: set_version
        run: |  # Output the version number to the version JSON file, which updates every time you commit
          version=$(date +'%Y%m%d.%H%M%S')
          echo "version=$version" >> "$GITHUB_OUTPUT"
          printf '{"version": "%s" }' "$version" > public/version.json
          printf '{"additionalNotice": "Build officially verified by Alex."}' > public/additional-notice.json

      - name: Build
        run: |  # npm ci is a clean install of npm, for testing environments/CI. The last line is so any 404 will be redirected to the home page
          npm ci && npm run build
          cp dist/index.html dist/404.html

      - name: Run tests
        run: |
          npx playwright install --with-deps chromium
          npm run test:coverage
          
      - name: Update coverage
        run: |
          coverage=$(jq '.total.lines.pct' coverage/coverage-summary.json)
          color=$(echo "$coverage < 80" | bc | awk '{if ($1) print "red"; else print "green"}')
          curl -s -X POST "https://pizza-factory.cs329.click/api/badge/${{ secrets.NET_ID }}/jwtpizzacoverage?label=Coverage&value=$coverage%25&color=$color" -H "authorization: bearer ${{ secrets.FACTORY_API_KEY }}"
          
      - name: Update GitHub Pages artifact # Packages up the dist directory for the next job to deploy to GitHub Pages
        uses: actions/upload-pages-artifact@v3 # This is a plugin, specifically defined to work with GitHub Pages
        with:
          path: dist/

  deploy:
    needs: build  # Build before you deploy
    permissions:  # Permissions to modify GitHub Pages for this repo
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4   # Looks for artifact created with the build job

  success:
    needs: [build, deploy]
    runs-on: ubuntu-latest
    steps:
      - name: Success Message
        run: echo "Good job, you succeeded in this amazing CI process."